// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chats": {
    params: {};
  };
  "/chats/chat/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chats" | "/chats/chat/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/chats.tsx": {
    id: "routes/chats";
    page: "/chats";
  };
  "./routes/chat.tsx": {
    id: "routes/chat";
    page: "/chats/chat/:id";
  };
};